-- MySQL Script generated by MySQL Workbench
-- 2023-01-18 08:30:06 +0530
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema deliverydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema deliverydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `deliverydb` ;
USE `deliverydb` ;

-- -----------------------------------------------------
-- Table `deliverydb`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `deliverydb`.`employee` ;

CREATE TABLE IF NOT EXISTS `deliverydb`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `tel` CHAR(12) NOT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `tel_UNIQUE` (`tel` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `deliverydb`.`user` ;

CREATE TABLE IF NOT EXISTS `deliverydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empId` INT NOT NULL,
  `role` ENUM("superadmin", "admin", "user") NOT NULL,
  `username` VARCHAR(12) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_1_idx` (`empId` ASC) VISIBLE,
  UNIQUE INDEX `emp_id_UNIQUE` (`empId` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_user_1`
    FOREIGN KEY (`empId`)
    REFERENCES `deliverydb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `deliverydb`.`shop` ;

CREATE TABLE IF NOT EXISTS `deliverydb`.`shop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `addressNo` VARCHAR(20) NOT NULL,
  `street` VARCHAR(100) NOT NULL,
  `city` VARCHAR(70) NOT NULL,
  `zipCode` VARCHAR(15) NULL,
  `email` VARCHAR(100) NOT NULL,
  `coordinateLong` VARCHAR(20) NULL,
  `coordinateLat` VARCHAR(20) NULL,
  `ownerId` INT NOT NULL,
  `tel` CHAR(12) NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hotel_owner_idx` (`ownerId` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_hotel_owner`
    FOREIGN KEY (`ownerId`)
    REFERENCES `deliverydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `deliverydb`.`order` ;

CREATE TABLE IF NOT EXISTS `deliverydb`.`order` (
  `id` INT NOT NULL,
  `hotelId` INT NOT NULL,
  `status` ENUM("PENDING", "SHARED", "CLAIMED", "DECLINED") NOT NULL DEFAULT 'PENDING',
  `deliveryId` INT NULL DEFAULT NULL,
  `sharerId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_delivery_idx` (`deliveryId` ASC) VISIBLE,
  INDEX `fk_order_share_idx` (`sharerId` ASC) VISIBLE,
  INDEX `fk_order_shop_idx` (`hotelId` ASC) VISIBLE,
  CONSTRAINT `fk_order_delivery`
    FOREIGN KEY (`deliveryId`)
    REFERENCES `deliverydb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_share`
    FOREIGN KEY (`sharerId`)
    REFERENCES `deliverydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_shop`
    FOREIGN KEY (`hotelId`)
    REFERENCES `deliverydb`.`shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
